<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>bee5a9d0-9d87-4179-8373-974149e3c603</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Adapters\" />
      <Folder Include="Configuration\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

</Project>
